noec:
  controls: # the ordering of these lists assigns
    modes:
      - { name: "control_simple", label: "Simple"}
      - { name: "control_advanced", label: "Advanced"}
      - { name: "demo_mcmc", label: "Demo: MCMC"}
      - { name: "demo_gc", label: "Demo: GD"}
    status:
      - { name: "uptime", label: "uptime [ticks]: "}
      - { name: "baseline", label: "baseline [km]: "}
      - { name: "likelihood", label: "likelihood [%]: "}
    parameters:
      - { name: "Dm32", label: "Dm32", units: "1E-3 eV", ADCMx: 1024, range: [2.2, 2.6], true_val: 2.3}
      - { name: "Th23", label: "Th23", units: "deg", ADCMx: 1024, range: [35, 55], true_val: 40 }
      - { name: "dcp", label: "dcp", units: "pi", ADCMx: 1024, range: [-1, 1], true_val: -0.33 }
      # - { name: "Th13", label: "Th13", units: "deg", ADCMx: 255, range: [ 8.1, 8.9 ], true_val: 8.8 }
      # - { name: "Baseline", label: "Baseline", units: "km", ADCMx: 255, range: [0, 6400] }
    likelihood:
      - {label: "likelihood", units: "%", range: [0,100]}
      - {label: "ml likelihood", units: "%", range: [0,100]}
      
  ui:
    scaffolding:
      page: { w: 1512, h: 1300 }
      mode_select: { w: 120, h: 40, fs: 15 }
      plots:
        trace: { w: 300, h: 150, ml: 50, mt: 35, mr: 5, mb: 20, nyticks: 3 }
        ml_trace: { w: 150, h: 150, ml: 50, mt: 35, mr: 5, mb: 20, nyticks: 3 }
        likelihood : {w: 300, h: 50, ml: 50, mt: 35, mr: 5, mb: 20, nyticks: 3 }
        flvtriangles: { w: 300, ml: 50, mt: 35, mr: 5, mb: 40, nticks: 3 }
        osc_probability: { w: 400, h: 160, ml: 60, mt: 35, mr: 5, mb: 40, nyticks: 3, nxticks: 5 }
        osc_events: { w: 400, h: 160, ml: 60, mt: 35, mr: 5, mb: 40, nyticks: 3, nxticks: 5 }
        two_d_likelihood: { w: 200, h: 200, ml: 40, mt: 20, mr: 0, mb: 40, nyticks: 5, nxticks: 5 }
        ml_walker: { w: 200, h: 200, ml: 40, mt: 20, mr: 0, mb: 40, nyticks: 5, nxticks: 5 }
      line: { w: 4 }
      labels:
        - { text: "Oscillations"}
        - { text: "Events"}
        - { text: "ML"}
    plots:
      traces:
        #- { parameter: "Th13" }
        - { parameter: "Dm32" }
        - { parameter: "Th23" }
        - { parameter: "dcp" }
      osc_probability:
        - { title: "Disappearance", ylabel: "P(numu -> numu)", xrange: [0,7], yrange: [0,1], osc_channel: [14, 14], dotrue: False }
        - { title: "Appearance", ylabel: "P(numu -> nue)", xrange: [0,7], yrange: [0,0.2], osc_channel: [14, 12], dotrue: False }
        - { title: "Appearance Bar", ylabel: "P(bnumu -> bnue)", xrange: [0,7], yrange: [0,0.2], osc_channel: [14, 12], dotrue: False }
      osc_events:
        - { title: "Disappearance", ylabel: "P(numu -> numu)", xrange: [0,7], yrange: [0,50], osc_channel: [14, 14], dotrue: True }
        - { title: "Appearance", ylabel: "P(numu -> nue)", xrange: [0,7], yrange: [0,10], osc_channel: [14, 12], dotrue: True }
        - { title: "Appearance Bar", ylabel: "P(bnumu -> bnue)", xrange: [0,7], yrange: [0,10], osc_channel: [14, 12], dotrue: True }
      machine_learning:
        - { title: "Machine Learning Appearance", ylabel: "P(numu -> nue)", xrange: [0,7], yrange: [0,10], osc_channel: [14, 12], dobar: True, truth: False, dotrue: True }
      flvtriangles:
        - {  }
      two_d_likelihood:
      - { title: "", ylabel: "Dm32", xlabel: "Th32",  xrange: [35, 55], yrange: [2.2, 2.6], parameters: ["Dm32", "Th23"] }
      - { title: "", ylabel: "Dm32", xlabel: "dcp",  xrange: [-1, 1], yrange: [2.2, 2.6], parameters: ["Dm32", "dcp"] }
      - { title: "", ylabel: "Th23", xlabel: "dcp",  xrange: [-1, 1], yrange: [35, 55], parameters: ["Th23", "dcp"] }

      ml_walker:
      - { title: "", ylabel: "Dm32", xlabel: "Th32",  xrange: [35, 55], yrange: [2.2, 2.6], parameters: ["Dm32", "Th23"] }
      - { title: "", ylabel: "Dm32", xlabel: "dcp",  xrange: [-1, 1], yrange: [2.2, 2.6], parameters: ["Dm32", "dcp"] }
      - { title: "", ylabel: "Th23", xlabel: "dcp",  xrange: [-1, 1], yrange: [35, 55], parameters: ["Th23", "dcp"] }
      likelihood:
        - { parameters: ["Dm32", "Th23"] }
    ml_status:
      - { name: "status", label: "status: "}
      - { name: "likelihood", label: "likelihood [%]: "} 
  input:
    flux:
      numode:
        numu:
          bin_edges: []
          bin_content: []
      nubarmode:
        numu:
          bin_edges: []
          bin_content: []
