# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vals.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'vals.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nvals.proto\x12\x04noec\"X\n\x07\x43ommand\x12\"\n\x03\x63md\x18\x01 \x01(\x0e\x32\x15.noec.Command.command\")\n\x07\x63ommand\x12\t\n\x05START\x10\x00\x12\x07\n\x03\x45ND\x10\x01\x12\n\n\x06UPDATE\x10\x02\" \n\x0cUpdateHeader\x12\x10\n\x08numbytes\x18\x01 \x01(\x05\"i\n\nUpdateBody\x12,\n\x06values\x18\x01 \x03(\x0b\x32\x1c.noec.UpdateBody.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEBODY_VALUESENTRY']._loaded_options = None
  _globals['_UPDATEBODY_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_COMMAND']._serialized_start=20
  _globals['_COMMAND']._serialized_end=108
  _globals['_COMMAND_COMMAND']._serialized_start=67
  _globals['_COMMAND_COMMAND']._serialized_end=108
  _globals['_UPDATEHEADER']._serialized_start=110
  _globals['_UPDATEHEADER']._serialized_end=142
  _globals['_UPDATEBODY']._serialized_start=144
  _globals['_UPDATEBODY']._serialized_end=249
  _globals['_UPDATEBODY_VALUESENTRY']._serialized_start=204
  _globals['_UPDATEBODY_VALUESENTRY']._serialized_end=249
# @@protoc_insertion_point(module_scope)
